name: tauqeer_portfolio
description: Portfolio for Tauqeer Ahmed.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">3.2.0 <=4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # FIREBASE STUFF
  firebase_core: ^4.12.1
  firebase_analytics: ^12.4.6

  cupertino_icons: ^1.0.9
  url_launcher: ^6.3.2
  google_fonts: ^8.2.1
  auto_size_text: ^3.0.0
  flutter_native_splash: ^2.4.8
  responsive_framework: ^1.5.1

#dependency_overrides:
#  win32: ^5.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/technologies/
    - assets/Tauqeer_Ahmed_Resume.pdf

flutter_native_splash:
  color: "#000000"
  image: assets/images/loader.gif
  branding: assets/images/name.png
  android: false
  ios: false